site_name: blog

pages:
- 博客: index.md
- 目录: index_目录.md
- python: python_python.md
- 规范: python_规范.md
- 缩进: python_缩进.md
- 编码: python_编码.md
- 导入: python_导入.md
- 库: python_库.md
- 董伟明的知乎回答: python_董伟明的知乎回答.md
- 赖明星的知乎回答: python_赖明星的知乎回答.md
- c: c_c.md
- c++: c++_c++.md

theme: readthedocs